In [12]:
import pandas as pd
import matplotlib.pyplot as plt
parks = pd.read_csv("../data/raw/nps_parks.csv")

#pulling national parks from dataset
national_parks = parks[parks["designation"].str.contains("National Park", na=False)]
print(national_parks.shape)
national_parks.head()

(60, 8)

,fullName,states,latitude,longitude,designation,parkCode,activities,entranceFees
1,Acadia National Park,ME,44.409286,-68.247501,National Park,acad,"Arts and Culture,Cultural Demonstrations,Astro...",6.0
24,Arches National Park,UT,38.722618,-109.586367,National Park,arch,"Arts and Culture,Astronomy,Stargazing,Biking,C...",30.0
29,Badlands National Park,SD,43.685848,-102.482942,National Park,badl,"Auto and ATV,Scenic Driving,Astronomy,Biking,C...",30.0
35,Big Bend National Park,TX,29.298178,-103.229790,National Park,bibe,"Auto and ATV,Scenic Driving,Astronomy,Stargazi...",30.0
42,Biscayne National Park,FL,25.490587,-80.210239,National Park,bisc,"Boating,Motorized Boating,Sailing,Boat Tour,Ca...",NaN

In [ ]:
national_parks.columns = ['Park', 'State', 'Latitude', 'Longitude','Designation', 'Park Code', 'Activities', 'Entrance Fees']
print(national_parks.columns)

#Dropping Designation column because we know that all data is from a national park
national_parks = national_parks.drop(columns = ['Designation'] )
print(national_parks.columns)

Index(['Park', 'State', 'Latitude', 'Longitude', 'Designation', 'Park Code',
       'Activities', 'Entrance Fees'],
      dtype='object')
Index(['Park', 'State', 'Latitude', 'Longitude', 'Park Code', 'Activities',
       'Entrance Fees'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 1 to 473
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Park           60 non-null     object
 1   State          60 non-null     object
 2   Latitude       60 non-null     float64
 3   Longitude      60 non-null     float64
 4   Park Code      60 non-null     object
 5   Activities     60 non-null     object
 6   Entrance Fees  40 non-null     float64
dtypes: float64(3), object(4)
memory usage: 3.8+ KB

In [14]:
#checking info
national_parks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 1 to 473
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Park           60 non-null     object
 1   State          60 non-null     object
 2   Latitude       60 non-null     float64
 3   Longitude      60 non-null     float64
 4   Park Code      60 non-null     object
 5   Activities     60 non-null     object
 6   Entrance Fees  40 non-null     float64
dtypes: float64(3), object(4)
memory usage: 3.8+ KB

In [16]:
print(national_parks.isnull().sum()) #20 missing values for entranceFees
missing_fees = national_parks[national_parks['Entrance Fees'].isnull()]
missing_fees

Park              0
State             0
Latitude          0
Longitude         0
Park Code         0
Activities        0
Entrance Fees    20
dtype: int64

,Park,State,Latitude,Longitude,Park Code,Activities,Entrance Fees
42,Biscayne National Park,FL,25.490587,-80.210239,bisc,"Boating,Motorized Boating,Sailing,Boat Tour,Ca...",NaN
87,Channel Islands National Park,CA,33.986801,-119.911273,chis,"Astronomy,Stargazing,Boating,Motorized Boating...",NaN
103,Congaree National Park,SC,33.791875,-80.748678,cong,"Camping,Backcountry Camping,Canoe or Kayak Cam...",NaN
112,Cuyahoga Valley National Park,OH,41.260939,-81.571167,cuva,"Arts and Culture,Craft Demonstrations,Cultural...",NaN
175,Gates Of The Arctic National Park & Preserve,AK,67.759616,-153.291776,gaar,"Camping,Backcountry Camping,Canoe or Kayak Cam...",NaN
186,Glacier Bay National Park & Preserve,AK,58.800867,-136.840758,glba,"Arts and Culture,Cultural Demonstrations,Auto ...",NaN
199,Great Basin National Park,NV,38.946174,-114.257978,grba,"Auto and ATV,Scenic Driving,Astronomy,Stargazi...",NaN
203,Great Smoky Mountains National Park,"NC,TN",35.601164,-83.508183,grsm,"Arts and Culture,Live Music,Auto and ATV,Sceni...",NaN
227,Hot Springs National Park,AR,34.524144,-93.063329,hosp,"Auto and ATV,Scenic Driving,Biking,Camping,Car...",NaN
249,Katmai National Park & Preserve,AK,58.622357,-155.012657,katm,"Boating,Camping,Backcountry Camping,Canoe or K...",NaN
250,Kenai Fjords National Park,AK,59.818044,-150.106502,kefj,"Astronomy,Stargazing,Boating,Boat Tour,Camping...",NaN
258,Kobuk Valley National Park,AK,67.356313,-159.200229,kova,"Boating,Camping,Backcountry Camping,Fishing,Fr...",NaN
261,Lake Clark National Park & Preserve,AK,60.574059,-153.555350,lacl,"Astronomy,Stargazing,Biking,Boating,Motorized ...",NaN
282,Mammoth Cave National Park,KY,37.197605,-86.130902,maca,"Astronomy,Stargazing,Biking,Boating,Camping,Ba...",NaN
322,New River Gorge National Park & Preserve,WV,37.868786,-80.999560,neri,"Arts and Culture,Theater,Auto and ATV,Scenic D...",NaN
328,North Cascades National Park,WA,48.711718,-121.206942,noca,"Auto and ATV,Scenic Driving,Biking,Road Biking...",NaN
445,Virgin Islands National Park,VI,18.342797,-64.741945,viis,"Arts and Culture,Craft Demonstrations,Cultural...",NaN
446,Voyageurs National Park,MN,48.483706,-92.838291,voya,"Arts and Culture,Cultural Demonstrations,Astro...",NaN
459,Wind Cave National Park,SD,43.580124,-103.439471,wica,"Auto and ATV,Scenic Driving,Biking,Road Biking...",NaN
465,Wrangell - St Elias National Park & Preserve,AK,61.418215,-142.602844,wrst,"Arts and Culture,Auto and ATV,ATV Off-Roading,...",NaN

In [ ]:
national_parks.loc[42, 'Entrance Fees'] = 0
national_parks.loc[87, 'Entrance Fees'] = 0
national_parks.loc[103, 'Entrance Fees'] = 0
national_parks.loc[112, 'Entrance Fees'] = 0
national_parks.loc[175, 'Entrance Fees'] = 0
national_parks.loc[186, 'Entrance Fees'] = 0
national_parks.loc[199, 'Entrance Fees'] = 0
national_parks.loc[203, 'Entrance Fees'] = 0
national_parks.loc[227, 'Entrance Fees'] = 0
national_parks.loc[249, 'Entrance Fees'] = 0
national_parks.loc[250, 'Entrance Fees'] = 0
national_parks.loc[258, 'Entrance Fees'] = 0
national_parks.loc[261, 'Entrance Fees'] = 0
national_parks.loc[282, 'Entrance Fees'] = 0
national_parks.loc[322, 'Entrance Fees'] = 0
national_parks.loc[328, 'Entrance Fees'] = 0
national_parks.loc[445, 'Entrance Fees'] = 0
national_parks.loc[446, 'Entrance Fees'] = 0
national_parks.loc[459, 'Entrance Fees'] = 0
national_parks.loc[465, 'Entrance Fees'] = 0

#checking missing values after searching entrance fee prices and manually entering
print(national_parks.isnull().sum())

Park             0
State            0
Latitude         0
Longitude        0
Park Code        0
Activities       0
Entrance Fees    0
dtype: int64

In [23]:
#counting each activity
all_activities = (national_parks['Activities'].str.split(',').explode().str.strip())
activity_counts = all_activities.value_counts()
activity_counts.head(20)

#adding a column of number of activities for each park
national_parks['Number of Activities'] = (national_parks['Activities'].str.split(',').str.len())

#moving new column to follow Activities
number_act = national_parks.pop('Number of Activities')
national_parks.insert(national_parks.columns.get_loc('Entrance Fees'),'Number of Activities',number_act)

#checking columns
national_parks.columns

Index(['Park', 'State', 'Latitude', 'Longitude', 'Park Code', 'Activities',
       'Number of Activities', 'Entrance Fees'],
      dtype='object')

In [24]:
#clean data - nps
national_parks.head()

,Park,State,Latitude,Longitude,Park Code,Activities,Number of Activities,Entrance Fees
1,Acadia National Park,ME,44.409286,-68.247501,acad,"Arts and Culture,Cultural Demonstrations,Astro...",46,6.0
24,Arches National Park,UT,38.722618,-109.586367,arch,"Arts and Culture,Astronomy,Stargazing,Biking,C...",18,30.0
29,Badlands National Park,SD,43.685848,-102.482942,badl,"Auto and ATV,Scenic Driving,Astronomy,Biking,C...",21,30.0
35,Big Bend National Park,TX,29.298178,-103.229790,bibe,"Auto and ATV,Scenic Driving,Astronomy,Stargazi...",24,30.0
42,Biscayne National Park,FL,25.490587,-80.210239,bisc,"Boating,Motorized Boating,Sailing,Boat Tour,Ca...",24,0.0