In [99]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import FuncFormatter

In [213]:
visits = pd.read_csv("../data/raw/visitation_data_np_2015-2025.csv")
print(visits.shape)
print(visits.columns)
visits.head()

(8316, 35)
Index(['ParkName', 'UnitCode', 'ParkType', 'Region', 'State', 'Year', 'Month',
       'RecreationVisits', 'NonRecreationVisits', 'RecreationHours',
       'NonRecreationHours', 'ConcessionerLodging', 'ConcessionerCamping',
       'TentCampers', 'RVCampers', 'Backcountry',
       'NonRecreationOvernightStays', 'MiscellaneousOvernightStays',
       'ParkNameTotal', 'UnitCodeTotal', 'ParkTypeTotal', 'RegionTotal',
       'StateTotal', 'YearTotal', 'RecreationVisitsTotal',
       'NonRecreationVisitsTotal', 'RecreationHoursTotal',
       'NonRecreationHoursTotal', 'ConcessionerLodgingTotal',
       'ConcessionerCampingTotal', 'TentCampersTotal', 'RVCampersTotal',
       'BackcountryTotal', 'NonRecreationOvernightStaysTotal',
       'MiscellaneousOvernightStaysTotal'],
      dtype='object')

,ParkName,UnitCode,ParkType,Region,State,Year,Month,RecreationVisits,NonRecreationVisits,RecreationHours,...,NonRecreationVisitsTotal,RecreationHoursTotal,NonRecreationHoursTotal,ConcessionerLodgingTotal,ConcessionerCampingTotal,TentCampersTotal,RVCampersTotal,BackcountryTotal,NonRecreationOvernightStaysTotal,MiscellaneousOvernightStaysTotal
0,Acadia NP,ACAD,National Park,Northeast,ME,2015,1,"12,578",600,"83,017",...,"47,100","14,452,151","47,100",0,0,"135,000","32,094","1,233",0,"8,343"
1,Acadia NP,ACAD,National Park,Northeast,ME,2015,2,"10,626",600,"70,132",...,"47,100","14,452,151","47,100",0,0,"135,000","32,094","1,233",0,"8,343"
2,Acadia NP,ACAD,National Park,Northeast,ME,2015,3,"18,062",600,"119,207",...,"47,100","14,452,151","47,100",0,0,"135,000","32,094","1,233",0,"8,343"
3,Acadia NP,ACAD,National Park,Northeast,ME,2015,4,"63,214",600,"366,642",...,"47,100","14,452,151","47,100",0,0,"135,000","32,094","1,233",0,"8,343"
4,Acadia NP,ACAD,National Park,Northeast,ME,2015,5,"187,205","7,500","1,062,976",...,"47,100","14,452,151","47,100",0,0,"135,000","32,094","1,233",0,"8,343"

In [214]:
#drop total values
visits = visits.drop(columns=['ParkNameTotal', 'UnitCodeTotal',
 'ParkTypeTotal', 'RegionTotal', 'StateTotal', 'YearTotal', 'RecreationVisitsTotal', 'NonRecreationVisitsTotal','RecreationHoursTotal', 'NonRecreationHoursTotal',
 'ConcessionerLodgingTotal', 'ConcessionerCampingTotal', 'TentCampersTotal', 'RVCampersTotal', 'BackcountryTotal', 'NonRecreationOvernightStaysTotal', 'MiscellaneousOvernightStaysTotal'])
visits.columns

Index(['ParkName', 'UnitCode', 'ParkType', 'Region', 'State', 'Year', 'Month',
       'RecreationVisits', 'NonRecreationVisits', 'RecreationHours',
       'NonRecreationHours', 'ConcessionerLodging', 'ConcessionerCamping',
       'TentCampers', 'RVCampers', 'Backcountry',
       'NonRecreationOvernightStays', 'MiscellaneousOvernightStays'],
      dtype='object')

In [215]:
#cleaning column names
visits.columns = ['Park Name', 'Unit Code', 'Park Type', 'Region', 'State', 'Year', 'Month', 'Recreation Visits', 'Non Recreation Visits', 'Recreation Hours', 'Non Recreation Hours', 'Concessioner Lodging', 'Concessioner Camping', 'Tent Campers', 'RV Campers', 'Backcountry', 'Non Recreation Overnight Stays', 'Miscellaneous Overnight Stays']
visits.columns

Index(['Park Name', 'Unit Code', 'Park Type', 'Region', 'State', 'Year',
       'Month', 'Recreation Visits', 'Non Recreation Visits',
       'Recreation Hours', 'Non Recreation Hours', 'Concessioner Lodging',
       'Concessioner Camping', 'Tent Campers', 'RV Campers', 'Backcountry',
       'Non Recreation Overnight Stays', 'Miscellaneous Overnight Stays'],
      dtype='object')

In [217]:
cols = ['Recreation Visits', 'Non Recreation Hours',
        'Concessioner Lodging', 'Concessioner Camping',
        'Tent Campers', 'RV Campers', 'Backcountry', 'Non Recreation Visits',
        'Recreation Hours',
        'Non Recreation Overnight Stays',
        'Miscellaneous Overnight Stays']
#removing commas from numbers
for col in cols:
    visits[col] = visits[col].astype(str).str.replace(',', '', regex=False)

visits[cols] = visits[cols].astype(int)

print(visits.info())
print(visits.isnull().sum())
visits.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8316 entries, 0 to 8315
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Park Name                       8316 non-null   object
 1   Unit Code                       8316 non-null   object
 2   Park Type                       8316 non-null   object
 3   Region                          8316 non-null   object
 4   State                           8316 non-null   object
 5   Year                            8316 non-null   int64
 6   Month                           8316 non-null   int64
 7   Recreation Visits               8316 non-null   int64
 8   Non Recreation Visits           8316 non-null   int64
 9   Recreation Hours                8316 non-null   int64
 10  Non Recreation Hours            8316 non-null   int64
 11  Concessioner Lodging            8316 non-null   int64
 12  Concessioner Camping            8316 non-null   int64
 13  Tent Campers                    8316 non-null   int64
 14  RV Campers                      8316 non-null   int64
 15  Backcountry                     8316 non-null   int64
 16  Non Recreation Overnight Stays  8316 non-null   int64
 17  Miscellaneous Overnight Stays   8316 non-null   int64
dtypes: int64(13), object(5)
memory usage: 1.1+ MB
None
Park Name                         0
Unit Code                         0
Park Type                         0
Region                            0
State                             0
Year                              0
Month                             0
Recreation Visits                 0
Non Recreation Visits             0
Recreation Hours                  0
Non Recreation Hours              0
Concessioner Lodging              0
Concessioner Camping              0
Tent Campers                      0
RV Campers                        0
Backcountry                       0
Non Recreation Overnight Stays    0
Miscellaneous Overnight Stays     0
dtype: int64

,Park Name,Unit Code,Park Type,Region,State,Year,Month,Recreation Visits,Non Recreation Visits,Recreation Hours,Non Recreation Hours,Concessioner Lodging,Concessioner Camping,Tent Campers,RV Campers,Backcountry,Non Recreation Overnight Stays,Miscellaneous Overnight Stays
0,Acadia NP,ACAD,National Park,Northeast,ME,2015,1,12578,600,83017,600,0,0,0,0,0,0,0
1,Acadia NP,ACAD,National Park,Northeast,ME,2015,2,10626,600,70132,600,0,0,0,0,0,0,0
2,Acadia NP,ACAD,National Park,Northeast,ME,2015,3,18062,600,119207,600,0,0,0,0,0,0,0
3,Acadia NP,ACAD,National Park,Northeast,ME,2015,4,63214,600,366642,600,0,0,0,0,0,0,0
4,Acadia NP,ACAD,National Park,Northeast,ME,2015,5,187205,7500,1062976,7500,0,0,10248,1737,44,0,753

In [73]:
clean_visits = visits
clean_visits.to_csv('../data/clean/visitation_data_clean.csv', index=False)

In [183]:
clean_visits['Unit Code'].unique()

array(['ACAD', 'ARCH', 'BADL', 'BIBE', 'BISC', 'BLCA', 'BRCA', 'CANY',
       'CARE', 'CAVE', 'CHIS', 'CONG', 'CRLA', 'CUVA', 'DEVA', 'DENA',
       'DRTO', 'EVER', 'GAAR', 'JEFF', 'GLBA', 'GLAC', 'GRCA', 'GRTE',
       'GRBA', 'GRSA', 'GRSM', 'GUMO', 'HALE', 'HAVO', 'HOSP', 'INDU',
       'ISRO', 'JOTR', 'KATM', 'KEFJ', 'KICA', 'KOVA', 'LACL', 'LAVO',
       'MACA', 'MEVE', 'MORA', 'NPSA', 'NERI', 'NOCA', 'OLYM', 'PEFO',
       'PINN', 'REDW', 'ROMO', 'SAGU', 'SEQU', 'SHEN', 'THRO', 'VIIS',
       'VOYA', 'WHSA', 'WICA', 'WRST', 'YELL', 'YOSE', 'ZION'],
      dtype=object)

In [211]:
parks = pd.read_csv("../data/raw/nps_parks.csv")
#pulling national parks from dataset
national_parks = parks[parks["designation"].str.contains("National Park", na=False)]
national_parks.columns = ['Park', 'State', 'Latitude', 'Longitude','Designation', 'Park Code', 'Activities', 'Entrance Fees']

#Dropping Designation column because we know that all data is from a national park
national_parks = national_parks.drop(columns = ['Designation'] )
print(national_parks.columns)

#adding all acitivites column
national_parks['Number of Activities'] = (national_parks['Activities'].str.split(',').str.len())
number_act = national_parks.pop('Number of Activities')
national_parks.insert(national_parks.columns.get_loc('Entrance Fees'),'Number of Activities',number_act)

#combining data
clean_visits['Unit Code'] = clean_visits['Unit Code'].str.lower()
combined = pd.merge(clean_visits, national_parks, left_on = 'Unit Code', right_on='Park Code', how='inner')
combined.columns 
combined = combined.drop(columns=['State_x'])
combined = combined.rename(columns={'State_y':'State'})
combined.to_csv("../data/clean/combined_nps_visitation.csv",index=False)

Index(['Park', 'State', 'Latitude', 'Longitude', 'Park Code', 'Activities',
       'Entrance Fees'],
      dtype='object')

In [210]:
entrance_sum = combined.groupby('Park Name').agg({'Recreation Visits':'sum', 'Entrance Fees':'first'}).reset_index()
entrance_sum.head()

     Park Name  Recreation Visits  Entrance Fees
0    Acadia NP           39227970            6.0
1    Arches NP           16813165           30.0
2  Badlands NP           11447855           30.0
3  Big Bend NP            5242161           30.0
4  Biscayne NP            6027079            NaN